version: '3.7'

services:
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8099:8080"
    depends_on:
      - customer-service
      - integration-service
      - location-service
      - order-service
      - payment-service
      - product-service
      - promotion-service
      - report-service
      - support-service

  customer-service:
    build:
      context: ./services/customer-service
    ports:
      - "8081:8081"

  integration-service:
    build:
      context: ./services/integration-service
    ports:
      - "8082:8082"

  location-service:
    build:
      context: ./services/location-service
    ports:
      - "8083:8083"

  order-service:
    build:
      context: ./services/order-service
    ports:
      - "8084:8084"

  payment-service:
    build:
      context: ./services/payment-service
    ports:
      - "8085:8085"

  product-service:
    build:
      context: ./services/product-service
    ports:
      - "8086:8086"

  promotion-service:
    build:
      context: ./services/promotion-service
    ports:
      - "8087:8087"

  report-service:
    build:
      context: ./services/report-service
    ports:
      - "8088:8088"

  support-service:
    build:
      context: ./services/support-service
    ports:
      - "8089:8089"
