version: '3.7'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.0
    networks:
      - broker-kafka
    volumes:
      - zookeeper-data:/data
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.0.0
    networks:
      - broker-kafka
    depends_on:
      - zookeeper
    volumes:
      - kafka-data:/var/lib/kafka
    ports:
      - 9093:9093
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafdrop:
    image: obsidiandynamics/kafdrop:3.27.0
    networks:
      - broker-kafka
    depends_on:
      - kafka
    ports:
      - 19000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:29092

  mongodb:
    image: mongo:latest
    networks:
      - broker-kafka
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: examplepassword
    volumes:
      - mongodb-data:/data/db

  mongo-express:
    image: mongo-express:latest
    networks:
      - broker-kafka
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: examplepassword
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb

networks:
  broker-kafka:
    driver: bridge

volumes:
  zookeeper-data:
  kafka-data:
  mongodb-data:
